export const TICK = "TICK"
export const INCREMENT = "INCREMENT"
export const DECREMENT = "DECREMENT"
export const RESET = "RESET"
export const LOAD_EXAMPLE_DATA = "LOAD_EXAMPLE_DATA"
export const LOADING_DATA_FAILURE = "LOADING_DATA_FAILURE"
export const I18N_SELECT = "I18N_SELECT"
export const INIT_MAIN_MENU = "INIT_MAIN_MENU"
export const ACTIVE_MENU_ITEM_CHANGED = "ACTIVE_MENU_ITEM_CHANGED"
export const ACTIVE_SUB_MENU_ITEM_CHANGED = "ACTIVE_SUB_MENU_ITEM_CHANGED"
//auth
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE'
